package com.bank.bian.marketriskmodels;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Market Risk Models
 *
 * Business Area:      Risk and Compliance
 * Business Domain:    Market and Operational Risk
 * Functional Pattern: Develop
 * Asset Type:         Market Risk Model
 * Control Record:     Market Risk Model Development Project
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Market Risk Models — BIAN Semantic API")
                .description("Service Domain 'Market Risk Models' (Develop pattern) "
                        + "operating on the 'Market Risk Model Development Project' control record.")
                .version("0.1.0"));
    }
}
